swagger: "2.0"
info:
  version: "0.0.1"
  title: blog API
# during dev, should point to your local machine
host: localhost:7070
# basePath prefixes all resource paths 
basePath: /

schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    get:
      summary: Returns users list
      operationId: getUsersList
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/User"

        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Add new user
      operationId: addUser
      parameters:
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: User has been add
        400:
          description: User already exists with this login

        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


  /users/{id}:
    delete:
      summary: Delete user
      operationId: DelUser
      parameters:
        - name: "id"
          in: "path"
          description: ""
          required: true
          type: "integer"
          format: "int64"


definitions:
  User:
    type: object
    required:
      - id
      - login
      - password
    properties:
      id:
        type: number
      login:
        type: string
      password:
        type: string
      fio:
        type:string


  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
